### PR TITLE
Catch variance equal to zero when scaling

### PR DESCRIPTION
**Pull request by dramanica**
This addresses #52 
There are now checks both in `big_scale()`, as well as in `big_randomSVD()` and `crossproductSelf()` and `tcroosprductSelf()`. Unit tests have been added to all functions that were affected.

### CODE REVIEW

**Comment by dramanica** [comment]
@privefl I went for belt and braces. There is now a check in the scaling function (in case it is also used in another package), but also in the affected functions within `bigstatsr`. I guess this adds a redundant check if using `big_scale()` within a function that already has the checks (e.g. `big_randomSVD`, but the check is relatively light weight, so I don't think it is a problem (but you are free to disagree!)

**Comment by privefl** [comment]
Thank you for your work on this!

I've added a few changes:
- only test if it is 0 (instead of negative) because I sometime use negative scalings
- test for near 0 instead of exactly 0
- warn (instead of error) for `big_scale()` because I sometime use this for computing the SD
- make sure `big_randomSVD()` also errors in parallel

**Comment by privefl** [comment]
Everything seems to work.
Tell me if you're okay with those changes.

**Comment by dramanica** [comment]
Fine with me!

**Comment by privefl** [comment]
close #52

**Pull request merged**
